name: "Publish to PyPI"

on:
  # Allow to publish to PyPI on worklow dispatch. Be careful as we can not
  # overwrite packages published to PyPI, so each run of this workflow needs
  # to be accompanied by a version bump
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "faasmctl/util/version.py"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Generate protobuf files to be included in the distribution"
        run: ./bin/gen_proto_files.py
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: "Install pypa/build"
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: "Build a binary wheel and a source tarball"
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: "Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
